services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: openjdk:17-jdk
    container_name: ${APP_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./app:/app
    command: >
      bash -c "java -jar /app/target/myapp-0.0.1-SNAPSHOT.jar
      --spring.profiles.active=prod
      --spring.datasource.url=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      --spring.datasource.username=${MYSQL_USER}
      --spring.datasource.password=${MYSQL_PASSWORD}"
    ports:
      - '${APP_PORT}:5050'
    restart: always

volumes:
  mysql_data:
